### ISSUE TITLE
Add tests for TechEmpower Framework Benchmarks

### ISSUE THREAD

**Issue by faustinoaq** [samueleaton/raze#1]
Hi @samueleaton , I like your framework documentation.

Would be possible to add Raze to https://github.com/TechEmpower/FrameworkBenchmarks ?

Raze is very similar to Kemal, Can I use Kemal tests as inspiration? https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Crystal/kemal

**Comment by faustinoaq** [comment]
I think is good to have another good framework like this in TFB.

**Comment by samueleaton** [comment]
Yeah, that'd be cool. But I don't think it is optimized for Crystal or kemal. The results don't look great. It shows Crystal as being slower than php, node.js, and ruby at json serialization

**Comment by faustinoaq** [comment]
Ok, Thanks for the advice
