### ISSUE TITLE
Amber Framework

### ISSUE THREAD

**Issue by elorest** [samueleaton/raze#15]
Hey Samuel. I'm also from Provo and have spent the last year working on crystal frameworks. The culmination of that work is the current state of https://amberframework.org.

I'm just writing to see if you've had a change to play with it at all or could be convince to come over and help us there. I believe that if we can make one awesome framework crystal could really become one of the next big things. 

If you'd be interested in discussing any of this with us please hit us up over on our gitter channel.

https://gitter.im/amberframework/amber

Have a great weekend.

**Comment by samueleaton** [comment]
Yo Isaac! Yeah I mostly built this for personal growth to see if I could and am not using it for production-grade stuff. I mainly wanted to try my hand at making something as minimal as Kemal but even more performant. 

I switched jobs recently and am working on a rather ambitious personal open-source project so my bandwidth is pretty maxed. But I'll check it out.

**Comment by elorest** [comment]
Yeah that makes sense. Good luck with the new project. If you ever need a fast, yet full featured framework, come checkout amber. Thanks for the ⭐️ btw.

How do you like Seattle having come from Provo?
