### ISSUE TITLE
websocket JS Client

### ISSUE THREAD

**Issue by joshua1** [samueleaton/raze#7]
Hi @samueleaton any plans to implement a JS websocket client or would any do (like the socket.io client)

**Comment by samueleaton** [comment]
Websockets are too easy to implement natively in JS to really add anything useful IMO. 

Here is a client/server example:

```ruby
# crystal
ws "/socket_1" do |ws, ctx|
  puts "new socket connection on socket 1!"

  ws.on_message do |msg|
    puts "message received by socket 1: #{msg}"
    ws.send("message received by socket 1")
  end

  ws.send("connected to websocket socket 1")
end
```

```javascript
// javascript
const exampleSocket = new WebSocket("ws://localhost:7777/channel_1")
exampleSocket.onopen = () => {
  exampleSocket.send("This is a message to the server")
}
exampleSocket.onmessage = evt => {
  console.log(evt.data)
}
```

...which will print this in the JS console:
![screen shot 2017-09-09 at 6 51 28 am](https://user-images.githubusercontent.com/9119269/30240778-644451ac-952b-11e7-9475-b6904dc1a411.png)

**Comment by joshua1** [comment]
Ok thats cool. I asked because of rooms in the docs, how would the client side JS look like connecting to 
```
ws "/room/:room_id" do |ws, ctx|
  room_id = ctx.params["room_id"]

  ws.on_message do |msg|
    puts "message received: #{msg}"
  end

  ws.on_close do
    puts "socket closed"
  end

  # send a message to the client
  ws.send("connected to room #{room_id}")
end
```
would that be a different socket connection?

**Comment by samueleaton** [comment]
That is just showing that you can take url parameters in the WebSocket path. So if you wanted to organize chatrooms by room ID or if you wanted to organize connected players to a video game by game ID thats how you could set it up. 

```ruby
# crystal
ws "/room/:room_id" do |ws, ctx|
  room_id = ctx.params["room_id"]

  ws.on_message do |msg|
    puts "message received: #{msg}"
  end

  ws.on_close do
    puts "socket closed"
  end

  # send a message to the client
  ws.send("connected to room #{room_id}")
end
```

```javascript
// javascript
const room1Socket = new WebSocket("ws://localhost:7777/room/room_a_1")
room1Socket.onopen = () => {
  room1Socket.send("This is a message to the server")
}
room1Socket.onmessage = evt => {
  console.log("message from server: ", evt.data)
}

const room2Socket = new WebSocket("ws://localhost:7777/room/room_a_1")
room2Socket.onopen = () => {
  room2Socket.send("This is a message to the server")
}
room2Socket.onmessage = evt => {
  console.log("message from server: ", evt.data)
}
```

...which would print to the JS console:
![screen shot 2017-09-10 at 12 49 05 pm](https://user-images.githubusercontent.com/9119269/30252392-7ce73304-9626-11e7-9eda-a2d56117d220.png)

**Comment by samueleaton** [comment]
That allows you to be able to verify that each user belongs to a room by writing your own middleware like this:

**WebSocket Connection Authenticator Middleware**

```ruby
# crystal
class RoomAuthenticator < Raze::WebSocketHandler
  def call(ws, ctx, done)
    room_id = ctx.params["room_id"]?

    # check redis or other state/session management to see if user has
    # access to this room by the `room_id`
    # note: try changing `true` to `false` to see how rejection is handled
    has_access = true

    if has_access
      # access granted, proceed to next middleware or block
      done.call
    else
      # access denied, respond with message and close the socket
      ws.send("access denied")
      ws.close
    end
  end
end
```

And then you would use that middleware in your socket definition like this:

**WebSocket Route**

```ruby
# crystal
ws "/room/:room_id", RoomAuthenticator.new do |ws, ctx|
  room_id = ctx.params["room_id"]

  ws.on_message do |msg|
    puts "message received: #{msg}"
  end

  ws.on_close do
    puts "socket closed"
  end

  # send a message to the client
  ws.send("connected to room #{room_id}")
end
```

**JavaScript Client**

```javascript
// javascript
const socket = new WebSocket("ws://localhost:7777/room/super_cool_room_1")
socket.onopen = () => {
  socket.send("This is a message to the server")
}
socket.onmessage = evt => {
  console.log("message from server: ", evt.data)
}
```

**Client Output**

If `has_access` is `true` in the middleware then the following will be printed to the JS console:
![screen shot 2017-09-10 at 12 55 43 pm](https://user-images.githubusercontent.com/9119269/30252434-8763aeb0-9627-11e7-98ee-b91eac2de401.png)


If `has_access` is `false` in the middleware then an "Access Denied"  message will be printed to the JS console:
![screen shot 2017-09-10 at 12 56 03 pm](https://user-images.githubusercontent.com/9119269/30252442-97e8444e-9627-11e7-88a3-134032c1c1fc.png)

**Comment by samueleaton** [comment]
If the client will only connect to a few sockets at a time you can do it that way, but if the client can potentially connect to several "rooms" at a time then it would be better to manage all of the rooms through a single socket and figure out how to keep track of all of the user's connected rooms on the backend and send relevant message to the client.

Hope this helps.

**Comment by joshua1** [comment]
Thanks @samueleaton it does help a lot
